/**
 * =====================================================================
 * AUTOGENERATED SUPABASE DATABASE TYPES
 * =====================================================================
 * Generated: 2025-01-08
 * Project: MyDispatch V32.5
 * Supabase Project: ygpwuiygivxoqtyoigtg
 * Tables: 57
 *
 * ⚠️ Generic types - for full type safety, run:
 * npx supabase gen types typescript --project-id ygpwuiygivxoqtyoigtg --schema public
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      alert_logs: {
        Row: { id: string; created_at: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; [key: string]: Json }
        Relationships: []
      }
      alert_policies: {
        Row: { id: string; created_at: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; [key: string]: Json }
        Relationships: []
      }
      audit_logs: {
        Row: { id: string; created_at: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; [key: string]: Json }
        Relationships: []
      }
      autonomous_execution_logs: {
        Row: { id: string; created_at: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; [key: string]: Json }
        Relationships: []
      }
      autonomous_system_config: {
        Row: { id: string; created_at: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; [key: string]: Json }
        Relationships: []
      }
      autonomous_system_stats: {
        Row: { id: string; created_at: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; [key: string]: Json }
        Relationships: []
      }
      autonomous_tasks: {
        Row: { id: string; created_at: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; [key: string]: Json }
        Relationships: []
      }
      agent_status: {
        Row: { id: string; created_at: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; [key: string]: Json }
        Relationships: []
      }
      ai_learning_patterns: {
        Row: { id: string; created_at: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; [key: string]: Json }
        Relationships: []
      }
      bookings: {
        Row: { id: string; created_at: string; company_id: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; company_id: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; company_id?: string; [key: string]: Json }
        Relationships: []
      }
      booking_history: {
        Row: { id: string; created_at: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; [key: string]: Json }
        Relationships: []
      }
      brain_logs: {
        Row: { id: string; created_at: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; [key: string]: Json }
        Relationships: []
      }
      brain_query_logs: {
        Row: { id: string; created_at: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; [key: string]: Json }
        Relationships: []
      }
      chat_consent: {
        Row: { id: string; created_at: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; [key: string]: Json }
        Relationships: []
      }
      chat_messages: {
        Row: { id: string; created_at: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; [key: string]: Json }
        Relationships: []
      }
      code_snippets: {
        Row: { id: string; created_at: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; [key: string]: Json }
        Relationships: []
      }
      companies: {
        Row: { id: string; created_at: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; [key: string]: Json }
        Relationships: []
      }
      component_registry: {
        Row: { id: string; created_at: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; [key: string]: Json }
        Relationships: []
      }
      cookie_consents: {
        Row: { id: string; created_at: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; [key: string]: Json }
        Relationships: []
      }
      cost_centers: {
        Row: { id: string; created_at: string; company_id: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; company_id: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; company_id?: string; [key: string]: Json }
        Relationships: []
      }
      customers: {
        Row: { id: string; created_at: string; company_id: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; company_id: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; company_id?: string; [key: string]: Json }
        Relationships: []
      }
      deletion_requests: {
        Row: { id: string; created_at: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; [key: string]: Json }
        Relationships: []
      }
      document_expiry_reminders: {
        Row: { id: string; created_at: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; [key: string]: Json }
        Relationships: []
      }
      document_templates: {
        Row: { id: string; created_at: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; [key: string]: Json }
        Relationships: []
      }
      drivers: {
        Row: { id: string; created_at: string; company_id: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; company_id: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; company_id?: string; [key: string]: Json }
        Relationships: []
      }
      email_templates: {
        Row: { id: string; created_at: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; [key: string]: Json }
        Relationships: []
      }
      entities_queue: {
        Row: { id: string; created_at: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; [key: string]: Json }
        Relationships: []
      }
      error_logs: {
        Row: { id: string; created_at: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; [key: string]: Json }
        Relationships: []
      }
      execution_runs: {
        Row: { id: string; created_at: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; [key: string]: Json }
        Relationships: []
      }
      feature_limits: {
        Row: { id: string; created_at: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; [key: string]: Json }
        Relationships: []
      }
      filter_presets: {
        Row: { id: string; created_at: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; [key: string]: Json }
        Relationships: []
      }
      gps_devices: {
        Row: { id: string; created_at: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; [key: string]: Json }
        Relationships: []
      }
      gps_positions: {
        Row: { id: string; created_at: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; [key: string]: Json }
        Relationships: []
      }
      health_checks: {
        Row: { id: string; created_at: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; [key: string]: Json }
        Relationships: []
      }
      heartbeat_history: {
        Row: { id: string; created_at: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; [key: string]: Json }
        Relationships: []
      }
      invoices: {
        Row: { id: string; created_at: string; company_id: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; company_id: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; company_id?: string; [key: string]: Json }
        Relationships: []
      }
      invoice_items: {
        Row: { id: string; created_at: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; [key: string]: Json }
        Relationships: []
      }
      knowledge_base: {
        Row: { id: string; created_at: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; [key: string]: Json }
        Relationships: []
      }
      known_issues: {
        Row: { id: string; created_at: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; [key: string]: Json }
        Relationships: []
      }
      monitoring_logs: {
        Row: { id: string; created_at: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; [key: string]: Json }
        Relationships: []
      }
      n8n_ai_conversations: {
        Row: { id: string; created_at: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; [key: string]: Json }
        Relationships: []
      }
      n8n_webhook_logs: {
        Row: { id: string; created_at: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; [key: string]: Json }
        Relationships: []
      }
      partners: {
        Row: { id: string; created_at: string; company_id: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; company_id: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; company_id?: string; [key: string]: Json }
        Relationships: []
      }
      partner_connections: {
        Row: { id: string; created_at: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; [key: string]: Json }
        Relationships: []
      }
      partner_requests: {
        Row: { id: string; created_at: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; [key: string]: Json }
        Relationships: []
      }
      performance_metrics: {
        Row: { id: string; created_at: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; [key: string]: Json }
        Relationships: []
      }
      profiles: {
        Row: { id: string; created_at: string; user_id: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; user_id: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; user_id?: string; [key: string]: Json }
        Relationships: []
      }
      special_accounts: {
        Row: { id: string; created_at: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; [key: string]: Json }
        Relationships: []
      }
      subscriptions: {
        Row: { id: string; created_at: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; [key: string]: Json }
        Relationships: []
      }
      system_logs: {
        Row: { id: string; created_at: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; [key: string]: Json }
        Relationships: []
      }
      tariff_system_v2: {
        Row: { id: string; created_at: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; [key: string]: Json }
        Relationships: []
      }
      temp_signups: {
        Row: { id: string; created_at: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; [key: string]: Json }
        Relationships: []
      }
      termination_logs: {
        Row: { id: string; created_at: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; [key: string]: Json }
        Relationships: []
      }
      vehicle_insurance: {
        Row: { id: string; created_at: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; [key: string]: Json }
        Relationships: []
      }
      vehicle_positions: {
        Row: { id: string; created_at: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; [key: string]: Json }
        Relationships: []
      }
      vehicles: {
        Row: { id: string; created_at: string; company_id: string; [key: string]: Json }
        Insert: { id?: string; created_at?: string; company_id: string; [key: string]: Json }
        Update: { id?: string; created_at?: string; company_id?: string; [key: string]: Json }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

// =====================================================================
// TYPE ALIASES FOR CONVENIENCE
// =====================================================================

export type Tables<
  PublicTableNameOrOptions extends
    | keyof (Database["public"]["Tables"])
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof (Database[PublicTableNameOrOptions["schema"]]["Tables"])
    : never = never
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? (Database[PublicTableNameOrOptions["schema"]]["Tables"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : PublicTableNameOrOptions extends keyof (Database["public"]["Tables"])
  ? (Database["public"]["Tables"])[PublicTableNameOrOptions] extends {
      Row: infer R
    }
    ? R
    : never
  : never

export type TablesInsert<
  PublicTableNameOrOptions extends
    | keyof Database["public"]["Tables"]
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof Database[PublicTableNameOrOptions["schema"]]["Tables"]
    : never = never
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? Database[PublicTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : PublicTableNameOrOptions extends keyof Database["public"]["Tables"]
  ? Database["public"]["Tables"][PublicTableNameOrOptions] extends {
      Insert: infer I
    }
    ? I
    : never
  : never

export type TablesUpdate<
  PublicTableNameOrOptions extends
    | keyof Database["public"]["Tables"]
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof Database[PublicTableNameOrOptions["schema"]]["Tables"]
    : never = never
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? Database[PublicTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : PublicTableNameOrOptions extends keyof Database["public"]["Tables"]
  ? Database["public"]["Tables"][PublicTableNameOrOptions] extends {
      Update: infer U
    }
    ? U
    : never
  : never

export type Enums<
  PublicEnumNameOrOptions extends
    | keyof Database["public"]["Enums"]
    | { schema: keyof Database },
  EnumName extends PublicEnumNameOrOptions extends { schema: keyof Database }
    ? keyof Database[PublicEnumNameOrOptions["schema"]]["Enums"]
    : never = never
> = PublicEnumNameOrOptions extends { schema: keyof Database }
  ? Database[PublicEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : PublicEnumNameOrOptions extends keyof Database["public"]["Enums"]
  ? Database["public"]["Enums"][PublicEnumNameOrOptions]
  : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof Database["public"]["CompositeTypes"]
    | { schema: keyof Database },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof Database[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never
> = PublicCompositeTypeNameOrOptions extends { schema: keyof Database }
  ? Database[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof Database["public"]["CompositeTypes"]
  ? Database["public"]["CompositeTypes"][PublicCompositeTypeNameOrOptions]
  : never
